import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";


import Todos from "~/components/Todos";
import {BsPencil} from 'react-icons/bs'
import {RiTodoLine} from 'react-icons/ri'
import {HiOutlinePaperAirplane} from 'react-icons/hi'
const Home: NextPage = () => {



const {data:sessionData} = useSession()




  return (
    <>
      <Head>
        {sessionData?<title>{sessionData.user.name}_Todos</title>:<title>Supa-Todo App</title>}
        
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main   className={ !sessionData?"flex min-h-screen flex-col justify-center items-center text-white   bg-black " :"flex min-h-screen flex-col text-white   bg-black "}        >
           <h1 className=" text-5xl md:text-8xl my-6 text-center ">supa-todo  </h1>
           <div className=" flex   items-center justify-center" >
           <h1 className="  font-light my-2 mx-2">Be Productive  </h1>
           <BsPencil/> 
           </div>
        <div className="  flex flex-col  items-center  px-2 py-10 ">


             { sessionData? <Todos/> : <><HiOutlinePaperAirplane className="  text-purple-900 mb-4 text-9xl "/><p></p></> }

             {
               sessionData?<><h1>Logged in as {sessionData.user.name}</h1> </> :<></>
             }

            <button className="  bg-purple-700 mt-2  px-4 py-1  rounded-md" 
            onClick={sessionData?()=>signOut():()=>signIn()}
            >
            {sessionData?"SignOut" :"SignIn"}
            </button>                    


        </div>
      </main>
    </>
  );
};

export default Home;


