import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";


import Todos from "~/components/Todos";
import {BsPencil} from 'react-icons/bs'
import {RiTodoLine} from 'react-icons/ri'
const Home: NextPage = () => {



const {data:sessionData} = useSession()




  return (
    <>
      <Head>
        {sessionData?<title>{sessionData.user.name}_Todos</title>:<title>Supa-Todo App</title>}
        
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="flex min-h-screen flex-col text-white justify-center  items-center  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
           <h1 className=" text-5xl ">supa-todo  </h1>
           <div className=" flex  items-center justify-center" >
           <h1 className="  font-light my-2 mx-2">Be Productive  </h1>
           <BsPencil/> 
           </div>
        <div className="  container flex flex-col  items-center  px-4 py-16 ">


             { sessionData? <Todos/> : <><RiTodoLine className=" text-green-500 mb-4 text-7xl "/><p></p></> }

             {
               sessionData?<><h1>Logged in as {sessionData.user.name}</h1> </> :<></>
             }

            <button className="  bg-purple-700 mt-2  px-4 py-1  rounded-md" 
            onClick={sessionData?()=>signOut():()=>signIn()}
            >
            {sessionData?"SignOut" :"SignIn"}
            </button>                    


        </div>
      </main>
    </>
  );
};

export default Home;


