import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";



import {BsPencil} from 'react-icons/bs'
import Link from "next/link";


const Home: NextPage = () => {



const {data:sessionData} = useSession()




  return (
    <>
      <Head>
        <title>Supa-Todo App</title>
        
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main   className="  text-white flex justify-center  w-screen bg-black/90"  >
        
        <div className="  min-h-screen w-full bg-black  md:w-[750px] flex justify-center items-center flex-col ">

        
           <h1 className=" text-4xl md:text-6xl my-2 text-center font-light ">supa-todo  </h1>
           <div className=" flex   items-center justify-center" >
           <h1 className="  font-light  text-sm my-2 mx-2 ">Be Productive  </h1>
           <BsPencil/> 
           </div>
               
          {/* <TiTickOutline className=" text-red-700 text-9xl"/> */}
  
           {sessionData?<button className=" absolute bottom-24   bg-white/10   mt-2  px-4 py-2  rounded-full" >
           <Link href={'/dashboard'}>Dashboard</Link> 
            </button>:<button className=" absolute bottom-24   bg-white/10   mt-2  px-4 py-2  rounded-full" 
            onClick={()=>signIn()}
            >
            Get Started
            </button>      }

                          


              </div>
        
      </main>
    </>
  );
};

export default Home;


